name: precommit-approved

on: push
  
jobs:
    precommit-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
      
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10.13"
      
            - name: Run precommit
              uses: pre-commit/action@v3.0.0