name: tests

on: push

env:
  PYTHON_VERSION: "3.8"

jobs:
  tests:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: cmd
        run: |
          ./install_openslide_windows.bat
          pip install openslide-python

      - name: Test
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -s tests tests --cov --cov-report term-missing
